"""Creacion de tablas Proveedor, Producto, CategoriProducto

Revision ID: 57e576a35cf4
Revises: 
Create Date: 2026-03-31 20:34:43.330904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e576a35cf4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AuthToken',
    sa.Column('id_token', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.Enum('USUARIO', 'CLIENTE'), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Integer(), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_addr', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id_token'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('Cliente',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('rfc', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('calle', sa.String(length=120), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('colonia', sa.String(length=120), nullable=True),
    sa.Column('ciudad', sa.String(length=80), nullable=True),
    sa.Column('estado', sa.String(length=80), nullable=True),
    sa.Column('pais', sa.String(length=80), nullable=True),
    sa.Column('cp', sa.String(length=10), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('categorias_producto',
    sa.Column('id_categoria_producto', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria_producto'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('proveedores',
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('rfc', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('calle', sa.String(length=120), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('colonia', sa.String(length=120), nullable=True),
    sa.Column('ciudad', sa.String(length=80), nullable=True),
    sa.Column('estado', sa.String(length=80), nullable=True),
    sa.Column('pais', sa.String(length=80), nullable=True),
    sa.Column('cp', sa.String(length=10), nullable=True),
    sa.Column('activo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_proveedor'),
    sa.UniqueConstraint('rfc')
    )
    op.create_table('Usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['Rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_categoria_producto', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=True),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('precio_venta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_actual', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('costo_unit_prom', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('activo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria_producto'], ['categorias_producto.id_categoria_producto'], ),
    sa.PrimaryKeyConstraint('id_producto'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('sku')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productos')
    op.drop_table('Usuario')
    op.drop_table('proveedores')
    op.drop_table('categorias_producto')
    op.drop_table('Rol')
    op.drop_table('Cliente')
    op.drop_table('AuthToken')
    # ### end Alembic commands ###
